### ISSUE TITLE
AttributeError: partially initialized module 'ssdp' has no attribute 'SimpleServiceDiscoveryProtocol' (most likely due to a circular import)

### ISSUE THREAD

**Issue by playaspec** [codingjoe/ssdp#13]
Hi.

I'm getting this error both with your example and the example code in the previous issue. Here is the full text:

>  \# ./ssdp.py 
> Traceback (most recent call last):
>   File "./ssdp.py", line 7, in <module>
>     import ssdp
>   File "/root/localMasq/ssdp.py", line 9, in <module>
>     class MyProtocol(ssdp.SimpleServiceDiscoveryProtocol):
> AttributeError: partially initialized module 'ssdp' has no attribute 'SimpleServiceDiscoveryProtocol' (most likely due to a circular import)

Happy to dig deeper on my end, but not really sure where to start. Thanks!

**Comment by codingjoe** [comment]
Hi @playaspec, I always pretty busy, so I'd absolutely appreciate the help. Let me know if you need anything. Best, Joe

**Comment by JuddTracy-DAS** [comment]
Rename your python file from ssdp.py to something else.  Python is trying to load the ssdp module from your example file and failing to find 'ssdp.SimpleServiceDiscoveryProtocol'

**Comment by codingjoe** [comment]
Good cath @JuddTracy-DAS
