### ISSUE TITLE
Example code request_msearch.py does not find all devices speaking ssdp

### ISSUE THREAD

**Issue by PeterStolz** [codingjoe/ssdp#15]
Hi,
when I run the code from example folder request_msearch.py I only find one device, yet running a different implementation of a ssdp browser like this:

```
import socket
import http.client
import io

class SSDPResponse(object):
    class _FakeSocket(io.BytesIO):
        def makefile(self, *args, **kw):
            return self
    def __init__(self, response):
        r = http.client.HTTPResponse(self._FakeSocket(response))
        r.begin()
        self.location = r.getheader("location")
        self.usn = r.getheader("usn")
        self.st = r.getheader("st")
        self.cache = r.getheader("cache-control").split("=")[1]
    def __repr__(self):
        return "<SSDPResponse({location}, {st}, {usn})>".format(**self.__dict__)

def discover(service, timeout=5, retries=1, mx=3):
    group = ("239.255.255.250", 1900)
    message = "\r\n".join([
        'M-SEARCH * HTTP/1.1',
        'HOST: {0}:{1}',
        'MAN: "ssdp:discover"',
        'ST: {st}','MX: {mx}','',''])
    socket.setdefaulttimeout(timeout)
    responses = {}
    for _ in range(retries):
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)
        sock.sendto(message.format(*group, st=service, mx=mx).encode('utf-8'), group)
        while True:
            try:
                response = SSDPResponse(sock.recv(1024))
                responses[response.location] = response
            except socket.timeout:
                break
    return list(responses.values())

if __name__ == '__main__':
    print(discover('ssdp:all'))
```

which is based on this https://gist.github.com/dankrause/6000248 I get a lot more devices. Looking at the wireshark traffic I noticed that some devices reply from and to seemingly random ports. One response from an IP camera was sent from 47993 to 52176.
Another device (My TP-Link Archer_MR200) is only responding to the requests of the custom script, even though they both target "ssdp:all". I confirmed this behavior multiple times and restarted all my devices by powering them off. The timeout is also not the issue, the devices reply in under 2 seconds. The only device that was found replied from port 1900. Am I overseeing some important functionality or do you have any idea what could cause this issue? Thanks in advance.

**Comment by codingjoe** [comment]
Hi @PeterStolz,

Thank you for reaching out. Interesting, can you try to add `proto=socket.IPPROTO_UDP` to line 42 in the example?


Best,
Joe

**Comment by PeterStolz** [comment]
Hi, thanks for replying.   
Unfortunately the problem remains. Adding `proto=socket.IPPROTO_UDP` has no affect on the result in my network. The library only finds 1 device whereas the script I added to this issue finds 5 devices in my network. I reran the scripts multiple times to confirm this behavior. Do you have any idea how we can troubleshoot this? I can only imagine it is related to the socket that is opened since the payload is the same in both scripts.

**Comment by codingjoe** [comment]
Hm… the problem is, that I only have a single device type that uses SSDP at my home right now. Therefore, it's hard for me to try reproducing this myself.

**Comment by codingjoe** [comment]
Maybe @StevenLooman  has an idea, he added the examples.

**Comment by StevenLooman** [comment]
Hey thank you for tagging me. I think the socket is not created properly. To be fair, I was mostly interested in receiving search requests and responding than searching itself, mostly for a little/short experiment. My own library, [https://github.com/StevenLooman/async_upnp_client](async_upnp_client), already covers the searching itself. (Though I don't want to grab the attention away from this repository!)

Looking at https://github.com/StevenLooman/async_upnp_client/blob/61965eada468efef5391bec5c498a0f9cf4658c3/async_upnp_client/ssdp.py#L198, a socket is created (giving more control) and a it does a few more `sock.setsockopt()` calls:
```

    # create socket
    sock = socket.socket(source[0], source[1], source[2])
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

    ..
        ..
        else:
            sock.setsockopt(socket.SOL_IP, socket.IP_MULTICAST_IF, source_ip.packed)
            sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)
            sock.setsockopt(
                socket.IPPROTO_IP,
                socket.IP_ADD_MEMBERSHIP,
                target_ip.packed + source_ip.packed,
            )
```

Specifically the `socket.IP_ADD_MEMBERSHIP` seems something worth trying.

**Comment by PeterStolz** [comment]
Hi, thanks for the quick reply!
After playing around with numerous socket options I noticed that the only difference in the IP Packets was the UDP payload.
After adding a second "\r\n" to the end of the request all of my devices responded. 
I opened a PR to fix this issue and the example now works perfectly.

**Comment by Rotaba** [comment]
Hey Guys, I also had a similar problem and was checking the issue. I wanted to drop by and say thanks to everyone for the input. Especially to @PeterStolz for opening the issue and following it through.

**Comment by StevenLooman** [comment]
Great!

**Comment by codingjoe** [comment]
Great team work! v1.1.0 should resolve the issue.
