### ISSUE TITLE
Example does nothing?

### ISSUE THREAD

**Issue by StevenLooman** [codingjoe/ssdp#9]
The example provided in the README does nothing, it seems. When I run it, I don't see any prints.

I'm running Python `3.8.0`, running Ubuntu 18.04.4 LTS.

Also, the example is missing the `socket` import.

Finally, for a prototype, I wish to respond to `M-SEARCH` requests. That should be possible with this library, right? I assume I should use port `1900` instead of the `1982` from the example.

**Comment by StevenLooman** [comment]
I've added some examples, please see #10

**Comment by codingjoe** [comment]
Hi @StevenLooman, thanks for reaching out. It's interesting to see, how many people use this package.
Anyhow, did your patch resolve all your issues or do we still need to fix things on bits of the documentation?
Best,
Joe

**Comment by StevenLooman** [comment]
The examples are enough for me. Perhaps copying the example from the README provides some consistency.

Also, showing the output in the README might be helpful.

**Comment by codingjoe** [comment]
I am proper downing in OSS work right now, so feel free to make those changes yourself 👍

**Comment by sanderjo** [comment]
I could use some help:

When I run the two example scripts from github simultaneously on my Ubuntu 20.04:

- request_msearch.py gives existing devices on my LAN (my Synology, an OpenWrt device). See dump below. But not:
- respond_msearch.py does not result in anything: nothing on stdout, so the print functions are not triggered

On my Windows, I do see some devices under Network: the synology, the openwrt, a google chromecast. But not anything from the ssdp scripts.

Maybe relevant: I have one WLAN interface, but Ubuntu has other interfaces too: docker, fixed ethernet (not connected), loopback ... could it be the scripts are using the wrong interface?

Anyway: help appreciated

```
$ python3 request_msearch.py  | grep -e SERVER -e LOCATION
header: ('SERVER', 'Synology/DSM/192.168.1.1')
header: ('LOCATION', 'http://192.168.1.1:5000/ssdp/desc-DSM-eth0.xml')
header: ('SERVER', 'Synology/DSM/192.168.1.1')
header: ('LOCATION', 'http://192.168.1.1:5000/ssdp/desc-DSM-eth0.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
header: ('SERVER', 'OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0')
header: ('LOCATION', 'http://192.168.1.254:5000/rootDesc.xml')
```

FWIW: output by mdns-scan:
```
$ mdns-scan 
+ googlerpc._googlerpc._tcp.local
+ Chromecast-c8a61db88dfffc7c70df049fc0e6a5dc._googlecast._tcp.local
+ c8a61db8-8dff-fc7c-70df-049fc0e6a5dc._googlezone._tcp.local
+ googlerpc-1._googlerpc._tcp.local
+ Google-Home-Mini-e1f164128df86139b4967899e2d68c11._googlecast._tcp.local
+ e1f16412-8df8-6139-b496-7899e2d68c11._googlezone._tcp.local
+ WITTE2004._smb._tcp.local
+ WITTE2004._device-info._tcp.local
+ Philips Hue - 721F4F._hue._tcp.local
+ Philips hue - 721F4F._hap._tcp.local
+ DiskStation._device-info._tcp.local
+ DiskStation._smb._tcp.local
+ BRIXIT._smb._tcp.local
+ BRIXIT._device-info._tcp.local
+ DiskStation._http._tcp.local
+ DiskStation._afpovertcp._tcp.local
```

**Comment by StevenLooman** [comment]
It has been a while, but lets give it a try. It's possible the things I state here are not correct, so please do investigate yourself.

Do you run the two scripts simultaneously? If I remember correctly, one has to/can respond to the other.

Most SSDP devices do regularly advertise themselves, perhaps that is what you're seeing from the `request_msearch.py`. Although the advertising is usually slow, while the discovery does result in a "storm" of responses. So if you get all those responses within the first 4 seconds, you're probably doing a `SEARCH`. You'll probably get more information without the `grep` command.

> Also, FWIW, on my Windows, I do see some devices under Network: the synology, the openwrt, a google chromecast. But not anything from the ssdp scripts.

Windows does more than just looking for these packets. I think it interprets the device description (the XML from the URLs you see in the `request_msearch.py` script.) You can try opening one of those URLs and see whats in it, for some context.

> Maybe relevant: I have one WLAN interface, but Ubuntu has other interfaces too: docker, fixed ethernet (not connected), loopback ... could it be the scripts are using the wrong interface? Or is MULTICAST_ADDRESS above that and listening to all interfaces?

It is possible though that the discovery-packet is sent from one of those other interfaces and thus never reaches the devices.

`mdns` is a different kind of service, namely `zeroconf`. See [Zero-configuration_networking](https://en.wikipedia.org/wiki/Zero-configuration_networking) and [Multicast_DNS](https://en.wikipedia.org/wiki/Multicast_DNS).

**Comment by sanderjo** [comment]
> Does the script `respond_msearch.py` run while (during) you're running `request_msearch.py`?

Yes

> If I remember correctly, one has to/can respond to the other.

Exactly. And that is not happeing. 

On your own system, can you repeat the test, so run the script `respond_msearch.py` run while (during) you're running `request_msearch.py`? Do you see your own system popping up?

**Comment by StevenLooman** [comment]
The combination of these two examples does not seem to work. Although my set-up is changed, it has at least one extra network interface so that might be the culprit.

I do have some other set-up code lying around, perhaps this helps for `respond_msearch.py`. YMMV, this is from another project where I was trying to respond to searches.

```python
    # Start the asyncio loop, bind to SSDP multicast address/port 1900.
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("0.0.0.0", 1900))
    connect = loop.create_datagram_endpoint(MyProtocol, sock=sock)
```

**Comment by sanderjo** [comment]
Thanks again.

I have better luck with https://stackoverflow.com/a/1794373/1492917 ... I do see SSDP multicast traffic (including what my python mini-script sends)  ... if only it would appear in Windows Network.

TBC.

Thanks

**Comment by StevenLooman** [comment]
If you want to make it appear in Windows Network you'll probably need a full blown UPnP-server implementation (i.e., something that serves up some XML and a SOAP implementation.)

What are you trying to achieve?

**Comment by sanderjo** [comment]
I want to announce the web interface of a download application on the LAN, and to have it visible on Windows.

For example: My Windows does see my Synology (and some other devices), and double-clicking on it, leads my webbrowser to  the web interface of the Synology. I want to have that for my (python) application

I'm assuming SSDP is the way to do that?

**Comment by StevenLooman** [comment]
I think SSDP is the first step, but I think you'll at least need something that serves up the XML/device description.

Take for example your router (assuming you have a consumer-level router.) It responds to a SSDP search request. In that response is a URL to the XML. Download this XML and take a look at it. You'll see some information about the device itself and the how a client can interface with it. If you can't find anything, try taking a look at the device description your Synology serves.

Perhaps it is enough to create a XML file with enough data and serve this. It might (not sure, something to try) to serve some basic information about the device, but no services/devices.

Hope this helps. Please let me know if you can get any results.

**Comment by sanderjo** [comment]
That helps indeed: 

`request_msearch.py` results in (amont others):

```
header: ('HOST', '239.255.255.250:190e 0')
header: ('EXT', '')
header: ('CACHE-CONTROL', 'max-age=100')
header: ('LOCATION', 'http://192.168.1.217:80/description.xml')
header: ('SERVER', 'Hue/1.0 UPnP/1.0 IpBridge/1.41.0')
header: ('hue-bridgeid', '001788FFFE721F4F')
header: ('ST', 'urn:schemas-upnp-org:device:basic:1')
header: ('USN', 'uuid:2f402f80-da50-11e1-9b23-001788721f4f')
```

That is my Philips Hue Bridge. But not the info that Windows shows about it.

So let's check that LOCATION http://192.168.1.217:80/description.xml :+1: 
```
$ lynx --dump http://192.168.1.217:80/description.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.217:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>veilingbrug (192.168.1.217)</friendlyName>
<manufacturer>Signify</manufacturer>
<manufacturerURL>http://www.philips-hue.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2015</modelName>
<modelNumber>BSB002</modelNumber>
<modelURL>http://www.philips-hue.com</modelURL>
<serialNumber>001788721f4f</serialNumber>
<UDN>uuid:2f402f80-da50-11e1-9b23-001788721f4f</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>
```

Ah! That looks like the info that is presented by Windows!

So, hypothesis: for Windows to show it, the SSDP must send a LOCATION with an URL to a XML info link. 

We're getting closer.

**Comment by StevenLooman** [comment]
Any luck?

**Comment by sanderjo** [comment]
> Any luck?

Yes, certainly! Thanks to your remark about the XML, I got it working. See

- text: https://github.com/sabnzbd/sabnzbd/issues/1641#issuecomment-713825819
- code: https://github.com/sabnzbd/sabnzbd/pull/1654

As I did not get the SSDP code working from this repo (so https://github.com/codingjoe/ssdp), I hand made some low level network code ... which works.

**Comment by StevenLooman** [comment]
Great!

Graag gedaan. :)

**Comment by aguaviva** [comment]
I am having the same issue, what is the fix?

**Comment by codingjoe** [comment]
There is a new version v1.2 which adds a CLI and tons of new documentation and examples. This should solve the issues described here.
